version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: riou_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=riou
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: ghcr.io/des-sist-corp-ufpb/projeto-eq20:latest
    build: .
    container_name: riou_app
    restart: always
    ports:
      - "127.0.0.1:8120:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/riou
      - S3_ENDPOINT_URL=https://s3.dsc.rodrigor.com
      - S3_PUBLIC_ENDPOINT=https://s3.dsc.rodrigor.com
      - S3_BUCKET=eq20
      - S3_ACCESS_KEY=eq20
      - S3_SECRET_KEY=2qMwQDKJ9je55RVcK0YIkd2A
      - S3_REGION=us-east-1
    depends_on:
      - db


volumes:
  pgdata:
